### ISSUE TITLE
Palettes are hard to close

### ISSUE THREAD

**Issue by icarito** [sugarlabs/sugar-web#126]
In Sugar palettes are closed when the mouse leaves the palette area.
They should be gone at least when clicking elsewhere.
(Edited to clarify, move z-index order to new issue).

**Comment by icarito** [comment]
I implemented a fix in Jappy. Will make a corresponding patch.

**Comment by quozl** [comment]
Closing per discussion in https://github.com/sugarlabs/sugar-web/pull/129
